[project]
name = "fastapi-sio-di"
version = "0.6.2"
description = "FastAPI-SIO-DI is a library tailored for integrating Socket.IO with FastAPI. It allows you to develop real-time WebSocket applications using the familiar FastAPI style (Dependency Injection, Pydantic models)."
requires-python = ">=3.10"
dependencies = [
    "python-socketio>=5.16.1",
    "msgpack>=1.0.0",
]

[project.optional-dependencies]
redis = [
    "redis>=4.0.0",
]

[dependency-groups]
dev = [
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
    "ruff>=0.15.9",
    "ty>=0.0.28",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "starlette>=0.45.0",
    "httpx>=0.28.0",
    "redis>=4.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fastapi_sio_di"]

[tool.ruff]
line-length = 120
target-version = "py310"
indent-width = 4

# Directories or files that do not need to be checked.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    ".idea",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "apps/backend/src/locales/types.py",
    "apps/backend/alembic",
    "**/tests/",
    "**/migrations/"
]

[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I001",
]
ignore = ["E501"]
per-file-ignores = { }
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
max-complexity = 10